package org.openlca.ecospold.model.process;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;
import org.openlca.ecospold.model.ILanguageCode;

@XmlType(name = "TISOLanguageCode")
@XmlEnum
enum LanguageCode implements ILanguageCode {

	@XmlEnumValue("ab")
	AB("ab"),
	@XmlEnumValue("aa")
	AA("aa"),
	@XmlEnumValue("af")
	AF("af"),
	@XmlEnumValue("sq")
	SQ("sq"),
	@XmlEnumValue("am")
	AM("am"),
	@XmlEnumValue("ar")
	AR("ar"),
	@XmlEnumValue("hy")
	HY("hy"),
	@XmlEnumValue("as")
	AS("as"),
	@XmlEnumValue("ay")
	AY("ay"),
	@XmlEnumValue("az")
	AZ("az"),
	@XmlEnumValue("ba")
	BA("ba"),
	@XmlEnumValue("eu")
	EU("eu"),
	@XmlEnumValue("bn")
	BN("bn"),
	@XmlEnumValue("dz")
	DZ("dz"),
	@XmlEnumValue("bh")
	BH("bh"),
	@XmlEnumValue("bi")
	BI("bi"),
	@XmlEnumValue("br")
	BR("br"),
	@XmlEnumValue("bg")
	BG("bg"),
	@XmlEnumValue("my")
	MY("my"),
	@XmlEnumValue("be")
	BE("be"),
	@XmlEnumValue("km")
	KM("km"),
	@XmlEnumValue("ca")
	CA("ca"),
	@XmlEnumValue("zh")
	ZH("zh"),
	@XmlEnumValue("co")
	CO("co"),
	@XmlEnumValue("hr")
	HR("hr"),
	@XmlEnumValue("cs")
	CS("cs"),
	@XmlEnumValue("da")
	DA("da"),
	@XmlEnumValue("nl")
	NL("nl"),
	@XmlEnumValue("en")
	EN("en"),
	@XmlEnumValue("eo")
	EO("eo"),
	@XmlEnumValue("et")
	ET("et"),
	@XmlEnumValue("fo")
	FO("fo"),
	@XmlEnumValue("fa")
	FA("fa"),
	@XmlEnumValue("fj")
	FJ("fj"),
	@XmlEnumValue("fi")
	FI("fi"),
	@XmlEnumValue("fr")
	FR("fr"),
	@XmlEnumValue("fy")
	FY("fy"),
	@XmlEnumValue("gl")
	GL("gl"),
	@XmlEnumValue("ka")
	KA("ka"),
	@XmlEnumValue("de")
	DE("de"),
	@XmlEnumValue("el")
	EL("el"),
	@XmlEnumValue("kl")
	KL("kl"),
	@XmlEnumValue("gn")
	GN("gn"),
	@XmlEnumValue("gu")
	GU("gu"),
	@XmlEnumValue("ha")
	HA("ha"),
	@XmlEnumValue("iw")
	IW("iw"),
	@XmlEnumValue("he")
	HE("he"),
	@XmlEnumValue("hi")
	HI("hi"),
	@XmlEnumValue("hu")
	HU("hu"),
	@XmlEnumValue("is")
	IS("is"),
	@XmlEnumValue("in")
	IN("in"),
	@XmlEnumValue("id")
	ID("id"),
	@XmlEnumValue("ia")
	IA("ia"),
	@XmlEnumValue("ie")
	IE("ie"),
	@XmlEnumValue("iu")
	IU("iu"),
	@XmlEnumValue("ik")
	IK("ik"),
	@XmlEnumValue("ga")
	GA("ga"),
	@XmlEnumValue("it")
	IT("it"),
	@XmlEnumValue("ja")
	JA("ja"),
	@XmlEnumValue("jw")
	JW("jw"),
	@XmlEnumValue("kn")
	KN("kn"),
	@XmlEnumValue("ks")
	KS("ks"),
	@XmlEnumValue("kk")
	KK("kk"),
	@XmlEnumValue("rw")
	RW("rw"),
	@XmlEnumValue("ky")
	KY("ky"),
	@XmlEnumValue("rn")
	RN("rn"),
	@XmlEnumValue("ko")
	KO("ko"),
	@XmlEnumValue("ku")
	KU("ku"),
	@XmlEnumValue("lo")
	LO("lo"),
	@XmlEnumValue("la")
	LA("la"),
	@XmlEnumValue("lv")
	LV("lv"),
	@XmlEnumValue("ln")
	LN("ln"),
	@XmlEnumValue("lt")
	LT("lt"),
	@XmlEnumValue("mk")
	MK("mk"),
	@XmlEnumValue("mg")
	MG("mg"),
	@XmlEnumValue("ms")
	MS("ms"),
	@XmlEnumValue("ml")
	ML("ml"),
	@XmlEnumValue("mt")
	MT("mt"),
	@XmlEnumValue("gv")
	GV("gv"),
	@XmlEnumValue("mi")
	MI("mi"),
	@XmlEnumValue("mr")
	MR("mr"),
	@XmlEnumValue("mo")
	MO("mo"),
	@XmlEnumValue("mn")
	MN("mn"),
	@XmlEnumValue("na")
	NA("na"),
	@XmlEnumValue("ne")
	NE("ne"),
	@XmlEnumValue("no")
	NO("no"),
	@XmlEnumValue("oc")
	OC("oc"),
	@XmlEnumValue("or")
	OR("or"),
	@XmlEnumValue("om")
	OM("om"),
	@XmlEnumValue("ps")
	PS("ps"),
	@XmlEnumValue("pl")
	PL("pl"),
	@XmlEnumValue("pt")
	PT("pt"),
	@XmlEnumValue("pa")
	PA("pa"),
	@XmlEnumValue("qu")
	QU("qu"),
	@XmlEnumValue("rm")
	RM("rm"),
	@XmlEnumValue("ro")
	RO("ro"),
	@XmlEnumValue("ru")
	RU("ru"),
	@XmlEnumValue("sm")
	SM("sm"),
	@XmlEnumValue("sg")
	SG("sg"),
	@XmlEnumValue("sa")
	SA("sa"),
	@XmlEnumValue("gd")
	GD("gd"),
	@XmlEnumValue("sr")
	SR("sr"),
	@XmlEnumValue("sh")
	SH("sh"),
	@XmlEnumValue("st")
	ST("st"),
	@XmlEnumValue("tn")
	TN("tn"),
	@XmlEnumValue("sn")
	SN("sn"),
	@XmlEnumValue("sd")
	SD("sd"),
	@XmlEnumValue("si")
	SI("si"),
	@XmlEnumValue("ss")
	SS("ss"),
	@XmlEnumValue("sk")
	SK("sk"),
	@XmlEnumValue("sl")
	SL("sl"),
	@XmlEnumValue("so")
	SO("so"),
	@XmlEnumValue("es")
	ES("es"),
	@XmlEnumValue("su")
	SU("su"),
	@XmlEnumValue("sw")
	SW("sw"),
	@XmlEnumValue("sv")
	SV("sv"),
	@XmlEnumValue("tl")
	TL("tl"),
	@XmlEnumValue("tg")
	TG("tg"),
	@XmlEnumValue("ta")
	TA("ta"),
	@XmlEnumValue("tt")
	TT("tt"),
	@XmlEnumValue("te")
	TE("te"),
	@XmlEnumValue("th")
	TH("th"),
	@XmlEnumValue("bo")
	BO("bo"),
	@XmlEnumValue("ti")
	TI("ti"),
	@XmlEnumValue("to")
	TO("to"),
	@XmlEnumValue("ts")
	TS("ts"),
	@XmlEnumValue("tr")
	TR("tr"),
	@XmlEnumValue("tk")
	TK("tk"),
	@XmlEnumValue("tw")
	TW("tw"),
	@XmlEnumValue("ug")
	UG("ug"),
	@XmlEnumValue("uk")
	UK("uk"),
	@XmlEnumValue("ur")
	UR("ur"),
	@XmlEnumValue("uz")
	UZ("uz"),
	@XmlEnumValue("vi")
	VI("vi"),
	@XmlEnumValue("vo")
	VO("vo"),
	@XmlEnumValue("cy")
	CY("cy"),
	@XmlEnumValue("wo")
	WO("wo"),
	@XmlEnumValue("xh")
	XH("xh"),
	@XmlEnumValue("ji")
	JI("ji"),
	@XmlEnumValue("yi")
	YI("yi"),
	@XmlEnumValue("yo")
	YO("yo"),
	@XmlEnumValue("zu")
	ZU("zu");
	private final String value;

	LanguageCode(String v) {
		value = v;
	}

	@Override
	public String value() {
		return value;
	}

	public static LanguageCode fromValue(String v) {
		if (v == null)
			return null;
		String trimmed = v.trim().toLowerCase();
		for (LanguageCode c : LanguageCode.values()) {
			if (c.value.equals(trimmed)) {
				return c;
			}
		}
		return null;
	}

}
